### ISSUE TITLE
old imports fail in new version

### ISSUE THREAD

**Issue by vlasvlasvlas** [vavalomi/ssaw#12]
Hi! i was testing this functionality, that works in older versions:

from ssaw.models import Questionnaire
from ssaw.utils import get_variables

--
with newest versions i got this error:
![image](https://github.com/vavalomi/ssaw/assets/4071796/06a8850a-385c-4e38-abf2-5ca34256ff6c)

what is the new way to call this imports ?

thanks!

**Comment by vavalomi** [comment]
The class was renamed to QuestionnaireDocument. This was changed some 3 years ago and there were a few more refactorings (there is no get_variables function anymore) while I was playing around with different ways to parse the questionnaire document. 

If you give a bit of detail of what information you're trying to extract from the structure I may be able to suggest a way that would work with the current version.
